language: python
python:
  - "3.6"
  - "pypy"
  - "pypy3"
deploy:
  provider: pypi
  user: "iamsinghrajat"
  password:
    secure: "LJCnWg/6HgUb0FfIMNGX6BIPng0OqiAqLCxnRwrvjbQS/ewTPaahE30V+wPrL5GfeLe4o8lYo62lHIvXydXNyt13jpzALIkdqR3XuNeiCbGUE6bOvdHfmZDeP7SkAb5yrPUW32oNetiFJaO0a4WyeVuD52eplYhVj0qHIrr0uPyIes9Wwdtv9t9+aJyuyVx9te7nov6Ln/03SsYErvA8DSlo8F1ZTAKUNwFTFWEBaRmMpKWCi69WVRH0qW0lriAWisWCwQUw2O1QcFolxzrARGp7yhuTbHeWyfo/ZkSXwUdw7AFAaJrfnlwaUKOan8B1p7m6SX8RZ24fHNiyDf/jFrc/cAht9AfSZudVDEMVzLq+67nmMb3LVL25wBfcTiLa/rTCpE1tY6n2AfRPf1HZphHr1FbUhi/6OyIPyjKgS4DdnYXvJmsfItoQ9PGH6w7YmOjmrooAfQTRsxbsfIYSr40pefY6RpSkcEAWizD8NpX6Uiq3dVVhf/55IbOB9BuAZMcDgW/R7hkk14APLAAHkvCdyVwSAx7BSKpJqJUwJHyk7XihkoB0/xEA6brKG1Aj2s4IpGhABinT3IDGNKLV2HbLTM3/sj7WBO40/0pb0jU6+H/AzTQeJyXyJIMoNL/dGoVFlvuOp3gnD4bznBpn05KEA4Dee80DjtMil60pEUs="
  skip_cleanup: true
  skip_existing: true
