language: generic
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "BiqZGyKb3Sx+cxzT9RBPYRaOqF+kYNyhUP6/1K+VHj2+rqCXqEMRDFcTtELG2PzujXeC4gKr3SwjXjQIEcJ1RSCgwrz6poC/xo0XKr4RMdd0sLBb1tHmWq/CxR1xUCfeVyu50GKmRVG59XD5VQrZ2fjKTZt9N1fd5Co/l7SAvhunPCez2TNhDH36uE6kFJpgVfFfs/xuvyu/YjkZ7FpSyYIuAIeFo2zYafDuGgyJhqPKaKS2ButuHOafc5+IvX5BBOpV81+TT1bDlSgWr4OvcMOVYgna9SymAdehdr1I5t+9nss3JHAYCjfXuerJhgPoHjvlEAeHr+cfKD84wxjeSOSJAeWnC74a2O+seX1p4mSvBbbFO9V2O+JQ8GoeadIxTU8Zh2C7rl5GiYOA6JVcM9XwZMbbV+UPgibltLYuSZG2cxI+tUefTXNFFCs/pAVtGhReVV94mclIAEhBimEtI+2o0PxWbirDK8GFAhNYh2j4JF0rEdmCVlCQ3WZUiwOb7ioJkITvBbgM0QhK7huTRIvigicSto95dbAbhIddp7kKjp6+a5nCEY6QmpoyAlF7XaDyNixZJDS3PbqiqvJKakUylfP8GOM68E4D3eTt5JQ9ggnFsbkHDLJM4UaxldiSQ/WFp1n++EBBhoFv4WPziLIen0Pmpu3/6CjSSNMjcEU="
  skip_cleanup: true
  skip_existing: true
